obj-$(CONFIG_NGBEVF) += ngbevf.o

ngbevf-objs := ngbe_main.o \
			 ngbe_mbx.o \
			 ngbe_common.o \
			 ngbe_param.o \
			 ngbe_txrx.o \
			 ngbe_vf.o \
			 ngbe_diag.o \
			 ngbe_ethtool.o \
			 ngbe_debugfs.o \
			 ngbe_configfs.o
