obj-$(CONFIG_IEE) += iee.o iee-gate.o iee-func.o stack-slab.o page-slab.o
ccflags-y += -I$(srctree)/mm
obj-$(CONFIG_IEE_SELINUX_P) += iee-selinuxp.o
ccflags-$(CONFIG_IEE_SELINUX_P) += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include -I$(objtree)/security/selinux
