# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Linux Wireless network device drivers for Realtek units
#

obj-$(CONFIG_RTL8180)		+= rtl818x/
obj-$(CONFIG_RTL8187)		+= rtl818x/
obj-$(CONFIG_RTLWIFI)		+= rtlwifi/
obj-$(CONFIG_RTL8XXXU)		+= rtl8xxxu/
obj-$(CONFIG_RTW88)		+= rtw88/
obj-$(CONFIG_RTW88_V2)		+= rtw88_v2/
obj-$(CONFIG_RTW89)		+= rtw89/
obj-$(CONFIG_RTW89_V2)		+= rtw89_v2/
obj-$(CONFIG_RTL8822CU)		+= rtl88x2CU/
obj-$(CONFIG_RTL8192FU)		+= rtl8192FU/
obj-$(CONFIG_RTL8822BU)		+= rtl88x2BU/

