/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_IEE_DEF_H
#define _LINUX_IEE_DEF_H

enum {
	IEE_OP_MEMCPY,
	IEE_OP_MEMSET,
	IEE_OP_SET_FREEPTR,
	IEE_OP_SPLIT_HUGE_PMD,
	IEE_OP_SET_TOKEN_PGD,
	IEE_OP_INIT_TOKEN,
	IEE_OP_INVALIDATE_TOKEN,
	IEE_OP_VALIDATE_TOKEN,
	IEE_OP_UNSET_TOKEN,
	IEE_OP_SET_TOKEN,
	IEE_OP_TEST_CLEAR_BIT,
	IEE_SET_SENSITIVE_PTE,
	IEE_UNSET_SENSITIVE_PTE,
#ifdef CONFIG_PTP
	IEE_OP_SET_PTE,
	IEE_OP_SET_PMD,
	IEE_OP_SET_PUD,
	IEE_OP_SET_P4D,
	IEE_OP_SET_PGD,
#endif
#ifdef CONFIG_IEE_SELINUX_P
	IEE_SEL_SET_STATUS_PG,
	IEE_SEL_SET_ENFORCING,
	IEE_SEL_SET_INITIALIZED,
	IEE_SEL_SET_POLICY_CAP,
	IEE_SEL_RCU_ASSIGN_POLICY,
#endif
	IEE_FLAG_END
};

#endif /* _LINUX_IEE_DEF_H */
