# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2015 - 2022 Beijing WangXun Technology Co., Ltd.
#
# Makefile for the Wangxun(R) 25/10GbE PCI Express ethernet driver
#

obj-$(CONFIG_TXGBEVF) += txgbevf.o

txgbevf-objs := txgbe_main.o \
              txgbe_common.o \
              txgbe_configfs.o \
              txgbe_ethtool.o \
			  txgbe_debugfs.o \
			  txgbe_diag.o \
			  txgbe_vf.o \
			  txgbe_txrx.o \
			  txgbe_mbx.o \
			  txgbe_param.o