[General]
auto-profiles = yes

[Mapping hdmi-stereo]
description = Digital Stereo (HDMI 0)
device-strings = hw:%f,0
channel-map = left,right
paths-output = hdmi-output-0
priority = 9
direction = output

[Mapping hdmi-stereo-extra1]
description = Digital Stereo (HDMI 1)
device-strings = hw:%f,1
channel-map = left,right
paths-output = hdmi-output-1
priority = 7
direction = output

[Mapping hdmi-stereo-extra2]
description = Digital Stereo (HDMI 2)
device-strings = hw:%f,2
channel-map = left,right
paths-output = hdmi-output-2
priority = 7
direction = output

[Mapping hdmi-stereo-extra3]
description = Digital Stereo (HDMI 3)
device-strings = hw:%f,3
paths-output = hdmi-output-3
channel-map = left,right
priority = 7
direction = output

[Mapping hdmi-stereo-extra4]
description = Digital Stereo (HDMI 4)
device-strings = hw:%f,4
paths-output = hdmi-output-4
channel-map = left,right
priority = 7
direction = output

[Mapping hdmi-stereo-extra5]
description = Digital Stereo (HDMI 5)
device-strings = hw:%f,5
paths-output = hdmi-output-5
channel-map = left,right
priority = 7
direction = output

